Mock fs-extra in fileUtil-test.js
After fs-extra was introduced in fileUtil.js, the unit tests started
failing with error "TypeError: polyfills is not a function". Not sure
why. The application still works as expected, so it seems to be related
to the jest runtime. Mocking fs-extra as it is not relevant for the
tests.